[build]
  # Build command for Next.js
  command = "npm run build"
  
  # Publish directory - Netlify will handle this automatically with the Next.js plugin
  publish = ".next"
  
[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  # Disable Next.js telemetry
  NEXT_TELEMETRY_DISABLED = "1"
  # Build optimization
  NPM_FLAGS = "--production=false"

# Plugin configuration for Next.js - MUST be first
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Caching headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Development settings
[dev]
  command = "npm run dev"
  port = 3000

# Important: Environment variables should be set in Netlify UI
# Go to Site Settings > Environment Variables and add:
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY  
# SUPABASE_SERVICE_ROLE_KEY
# NEXT_PUBLIC_SITE_URL (set to your Netlify app URL, e.g., https://your-app.netlify.app)
# MONGODB_URI
# SENDGRID_API_KEY
# FROM_EMAIL